{{- if .Values.ingress.enabled }}
  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: {{ .Values.ingress.name }}
    namespace: {{ .Values.ingress.namespace }}
    annotations:
      kubernetes.io/ingress.class: nginx
    labels:
      app: {{ .Values.ingress.name }}
  spec:
    rules:
      - host: {{ .Values.ingress.host }}
        http:
          paths:
            - pathType: Prefix
              path: {{ .Values.ingress.path }}
              backend:
                serviceName: {{ .Values.ingress.serviceName }}
                servicePort: {{ .Values.ingress.servicePort }}
{{- end }}