{{- if .Values.canaryRollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.canaryRollout.appName }}
  namespace: {{ .Values.canaryRollout.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.appName }}
      role: {{ .Values.deployment.role }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appName }}
        role: {{ .Values.deployment.role }}
    spec:
      containers:
      - name: {{ .Values.deployment.containerName }}
        image: "{{ .Values.deployment.imageRepository }}:{{ .Values.deployment.imageTag }}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.deployment.port }}
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      # Reference to a Service which the controller will update to point to the canary ReplicaSet
      canaryService: {{ .Values.canaryRollout.canaryService }}
      # Reference to a Service which the controller will update to point to the stable ReplicaSet
      stableService: {{ .Values.canaryRollout.stableService }}
      trafficRouting:
        nginx:
          # Reference to an Ingress which has a rule pointing to the stable service (e.g. rollouts-demo-stable)
          # This ingress will be cloned with a new name, in order to achieve NGINX traffic splitting.
          stableIngress: {{ .Values.canaryRollout.stableIngress }}
      steps:
      - setWeight: 20
      - pause: {duration: 40s}
      - setWeight: 40
      - pause: {duration: 20s}
      - setWeight: 60
      - pause: {duration: 20s}
      - setWeight: 80
      - pause: {duration: 10s}
{{- end }}