global:
  chartName: orders
orders:
  # Deployment object
  deployment:
    enabled: false
    imageTag: sha256:2d8a12a1d2dff5abeceaea59c897d807e8627c4e4809ec0236eb442df3d350f5
  # Updated (New) Deployment resource
  newDeployment:
    enabled: true
    name: orders
    namespace: ecommerce
    replicas: 3
    appName: orders
    role: api
    containerName: orders-container
    imageRepository: lukondefmwila/ecommerce-orders
    imageTag: sha256:a4cd4c95ac09725df972165f9d23d3780175e1b7c7d28f37cb1b3db05719b33a
    port: 3003
  # Horizontal Pod Autoscaler
  hpa:
    enabled: false
  # Service Account object
  serviceAccount:
    enabled: true
    name: orders-service-account
    namespace: ecommerce
  # Stable Service object
  service:
    enabled: true
    name: orders-service
    namespace: ecommerce
    appName: orders
    type: ClusterIP
    servicePort: 3003
    targetPort: 3003
  # Canary Service object (for Argo Rollouts)
  canaryService:
    enabled: false
  # Namespace object
  namespace:
    enabled: false
  # Ingress 
  ingress:
    enabled: false
  # Canary Rollout # Canary Service object (for Argo Rollouts)
  canaryRollout:
    enabled: false
