global:
  chartName: orders
orders:
  # Deployment object
  deployment:
    enabled: true
    name: orders
    namespace: ecommerce
    replicas: 3
    appName: orders
    role: api
    containerName: orders-container
    imageRepository: lukondefmwila/ecommerce-orders
    imageTag: sha256:1c7ff51e5e461ead541139569998fc6428892da580be421e6689023fe6d7bba5
    port: 3003
  # Stable Service object
  service:
    enabled: true
    name: orders-service
    namespace: ecommerce
    appName: orders
    type: LoadBalancer
    servicePort: 3003
    targetPort: 3003
  # Canary Service object
  canaryService:
    enabled: false
  # Service Account object
  serviceAccount:
    enabled: true
    name: orders-service-account
    namespace: ecommerce
  # Namespace object
  namespace:
    enabled: false
  # Ingress 
  ingress:
    enabled: true
    name: orders
    namespace: ecommerce
    host: lukemwila.com
    path: "/"
    serviceName: orders-service
    servicePort: 3003
  # Horizontal Pod Autoscaler
  hpa:
    enabled: true
    name: orders-hpa
    namespace: ecommerce
    appName: orders
  # Canary Rollout
  canaryRollout:
    enabled: false
