global:
  chartName: orders
orders:
  # Deployment object
  deployment:
    enabled: true
    name: orders
    namespace: ecommerce
    replicas: 3
    appName: orders
    role: api
    containerName: orders-container
    imageRepository: lukondefmwila/ecommerce-orders
    imageTag: 0.1.2
    port: 3003
  # Updated (New) Deployment resource
  newDeployment:
    enabled: true
  # Horizontal Pod Autoscaler
  hpa:
    enabled: true 
    name: orders-hpa
    appName: orders
    namespace: ecommerce
  # Service Account object
  serviceAccount:
    enabled: true
    name: orders-service-account
    namespace: ecommerce
  # Stable Service object
  service:
    enabled: false
  # Canary Service object (for Argo Rollouts)
  canaryService:
    enabled: false
  # Namespace object
  namespace:
    enabled: false
  # Ingress 
  ingress:
    enabled: false
  # Canary Rollout # Canary Service object (for Argo Rollouts)
  canaryRollout:
    enabled: false
