global:
  chartName: orders
orders:
  # Deployment object
  deployment:
    enabled: true
    name: orders
    namespace: ecommerce
    replicas: 3
    appName: orders
    role: api
    containerName: orders-container
    imageRepository: lukondefmwila/ecommerce-orders
    imageTag: sha256:a4cd4c95ac09725df972165f9d23d3780175e1b7c7d28f37cb1b3db05719b33a
    port: 3003
  # Horizontal Pod Autoscaler
  hpa:
    enabled: true
    name: orders-hpa
    appName: orders
    namespace: ecommerce
  # Service Account object
  serviceAccount:
    enabled: true
    name: orders-service-account
    namespace: ecommerce
  # Stable Service object
  service:
    enabled: false
  # Canary Service object (for Argo Rollouts)
  canaryService:
    enabled: false
  # Namespace object
  namespace:
    enabled: false
  # Ingress 
  ingress:
    enabled: false
  # Canary Rollout # Canary Service object (for Argo Rollouts)
  canaryRollout:
    enabled: false
